import React,{FormEvent,useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import'./styles.css';

type Shift={id:string;branchName:string;address:string|null;startsAt:string;endsAt:string;breakMinutes:number;checkInAt:string|null;checkOutAt:string|null};
const env=(import.meta as any).env as Record<string,string|undefined>;
const API=env.VITE_EMPLOYEE_API_URL??'http://localhost:4100';
const companyId=new URLSearchParams(location.search).get('company')||env.VITE_COMPANY_ID||'';

function App(){
 const[token,setToken]=useState(()=>sessionStorage.getItem('attendra_employee_token')||'');
 const[employee,setEmployee]=useState<any>(null);const[shifts,setShifts]=useState<Shift[]>([]);const[error,setError]=useState('');
 const headers=()=>({'Content-Type':'application/json','Authorization':`Bearer ${token}`});
 const load=async()=>{if(!token)return;try{const[a,b]=await Promise.all([fetch(`${API}/v1/employee/me`,{headers:headers()}),fetch(`${API}/v1/employee/shifts`,{headers:headers()})]);if(a.status===401||b.status===401)throw new Error('SESSION');const aj=await a.json(),bj=await b.json();if(!a.ok||!b.ok)throw new Error('LOAD');setEmployee(aj.employee);setShifts(bj.shifts)}catch(e:any){if(e.message==='SESSION'){sessionStorage.removeItem('attendra_employee_token');setToken('')}else setError('Unable to load your Attendra account.')}};
 useEffect(()=>{load()},[token]);
 const login=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');if(!companyId){setError('This employee link is not connected to a company.');return}const f=new FormData(e.currentTarget);const r=await fetch(`${API}/v1/employee/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,employeeNumber:f.get('employeeNumber'),pin:f.get('pin')})});const j=await r.json();if(!r.ok){setError('Employee number or PIN is incorrect.');return}sessionStorage.setItem('attendra_employee_token',j.token);setToken(j.token)};
 const logout=()=>{sessionStorage.removeItem('attendra_employee_token');setToken('');setEmployee(null);setShifts([])};
 if(!token)return <main className="shell"><section className="login card"><div className="eyebrow">ATTENDRA EMPLOYEE</div><h1>My workday</h1><p>View your shifts, attendance status and daily work information.</p><form onSubmit={login}><label>Employee number<input name="employeeNumber" required autoComplete="username"/></label><label>PIN<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{4,12}" required autoComplete="current-password"/></label>{error&&<div className="error">{error}</div>}<button>Sign in</button></form></section></main>;
 const now=Date.now();const today=shifts.find(s=>new Date(s.startsAt).toDateString()===new Date().toDateString())||null;const upcoming=shifts.filter(s=>new Date(s.startsAt).getTime()>now).slice(0,8);
 return <main className="shell"><header><div><div className="eyebrow">{employee?.companyName||'ATTENDRA'}</div><h1>Hello {employee?.firstName||''}</h1></div><button className="ghost" onClick={logout}>Sign out</button></header><section className="card hero"><h2>Today</h2>{today?<><div className="shift-time">{new Date(today.startsAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} – {new Date(today.endsAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div><p>{today.branchName}{today.address?` · ${today.address}`:''}</p><div className="status-grid"><span>Check in<strong>{today.checkInAt?new Date(today.checkInAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Not yet'}</strong></span><span>Check out<strong>{today.checkOutAt?new Date(today.checkOutAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Not yet'}</strong></span><span>Break<strong>{today.breakMinutes} min</strong></span></div></>:<p>No shift is scheduled for today.</p>}</section><section className="card"><h2>Upcoming shifts</h2>{upcoming.length?upcoming.map(s=><article className="shift" key={s.id}><div><strong>{new Date(s.startsAt).toLocaleDateString([],{weekday:'short',day:'numeric',month:'short'})}</strong><span>{s.branchName}</span></div><div>{new Date(s.startsAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} – {new Date(s.endsAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div></article>):<p>No upcoming shifts.</p>}</section><section className="card muted"><h2>Daily activities & outcome notes</h2><p>This area is reserved for assigned activities, completed work, issues and end-of-day handover notes. It will be enabled in the next Attendra employee-workflow phase.</p></section></main>}
createRoot(document.getElementById('root')!).render(<App/>);
