import React,{useEffect,useState} from 'react';
import {addDays,dateKey,labelDay,monday,onDay,shiftTime} from './schedule-dates';
type Shift={id:string;branchName:string;startsAt:string;endsAt:string;breakMinutes:number;checkInAt:string|null;checkOutAt:string|null};
type Interval={startsAt:string;endsAt:string};
export function EmployeeSchedule({api,token,timeZone,refresh}:{api:string;token:string;timeZone:string;refresh:number}){
 const today=dateKey(new Date(),timeZone),[anchor,setAnchor]=useState(today),[view,setView]=useState<'today'|'week'|'month'>('week'),[selected,setSelected]=useState(today);
 const [data,setData]=useState<{shifts:Shift[];unavailability:Interval[];notices:{id:string;message:string;createdAt:string}[]}>({shifts:[],unavailability:[],notices:[]}),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const firstMonth=anchor.slice(0,7)+'-01';const from=view==='month'?monday(firstMonth):view==='week'?monday(anchor):anchor,to=addDays(from,view==='month'?41:view==='week'?6:0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');fetch(`${api}/v1/employee/schedule?from=${from}&to=${to}`,{headers:{Authorization:`Bearer ${token}`},signal:abort.signal}).then(async r=>{if(!r.ok)throw Error(r.status===401?'Your session ended. Sign out and sign in again.':'Unable to load your schedule.');return r.json()}).then(d=>{if(!abort.signal.aborted)setData(d)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[api,token,from,to,refresh]);
 const navigate=(direction:number)=>{if(view==='month'){const d=new Date(`${firstMonth}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+direction);const next=d.toISOString().slice(0,10);setAnchor(next);setSelected(next)}else{const next=addDays(anchor,direction*(view==='week'?7:1));setAnchor(next);setSelected(next)}};
 const days=Array.from({length:view==='month'?42:view==='week'?7:1},(_,i)=>addDays(from,i));
 const card=(day:string)=>{const list=data.shifts.filter(s=>onDay(s,day,timeZone)),unavailable=data.unavailability.some(u=>onDay(u,day,timeZone));return <article className="scheduleDay" key={day}><h3>{labelDay(day)}{day===today&&<small> · Today</small>}</h3>{unavailable&&<p className="scheduleWarning">Marked unavailable{list.length?' — contact your manager about these shifts.':'.'}</p>}{list.length?list.map(s=><div className="scheduleShift" key={s.id}><strong>{s.branchName}</strong><span>{shiftTime(s,timeZone)}</span><small>{s.breakMinutes} min break · {s.checkOutAt?'Completed':s.checkInAt?'Checked in':'Scheduled'}</small></div>):<p className="muted">No shift scheduled</p>}</article>};
 const total=data.shifts.filter(s=>dateKey(s.startsAt,timeZone)>=from&&dateKey(s.startsAt,timeZone)<=to).reduce((sum,s)=>sum+Math.max(0,(Date.parse(s.endsAt)-Date.parse(s.startsAt))/3600000-s.breakMinutes/60),0);
 return <section className="panel"><div className="panelHead"><div><h2>My schedule</h2><span>{timeZone} · {view==='month'?labelDay(firstMonth,{month:'long',year:'numeric'}):`${labelDay(from)}${to!==from?' – '+labelDay(to):''}`}</span></div><div className="scheduleControls">{(['today','week','month'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);setAnchor(today);setSelected(today)}}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div></div><div className="scheduleControls"><button aria-label="Previous period" onClick={()=>navigate(-1)}>←</button><button onClick={()=>{setAnchor(today);setSelected(today)}}>Today</button><button aria-label="Next period" onClick={()=>navigate(1)}>→</button><span>{view==='week'?`${total.toFixed(1)} scheduled hours after breaks`:''}</span></div>{error&&<p className="errorBox" role="alert">{error}</p>}{loading?<p role="status">Loading schedule…</p>:<>{view==='month'?<><div className="monthGrid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><strong className="calendarHeading" key={d}>{d}</strong>)}{days.map(day=>{const shifts=data.shifts.filter(s=>onDay(s,day,timeZone));return <button className={`monthDay ${day.slice(0,7)!==anchor.slice(0,7)?'muted':''} ${day===selected?'selected':''}`} key={day} aria-label={`${labelDay(day)}, ${shifts.length} shifts`} aria-pressed={day===selected} onClick={()=>setSelected(day)}><strong>{Number(day.slice(-2))}{day===today?' •':''}</strong>{shifts.slice(0,2).map(s=><span key={s.id}>{s.branchName}</span>)}{shifts.length>2&&<small>+{shifts.length-2} more</small>}{data.unavailability.some(u=>onDay(u,day,timeZone))&&<small>Unavailable</small>}</button>})}</div>{card(selected)}</>:<div className="employeeWeek">{days.map(card)}</div>}</>}{data.notices.length>0&&<details className="scheduleNotices"><summary>Schedule updates</summary>{data.notices.map(n=><p key={n.id}>{n.message}<small> · {new Date(n.createdAt).toLocaleString(undefined,{timeZone})}</small></p>)}</details>}</section>;
}
