import React, { FormEvent, useEffect, useState } from 'react';
import { EmployeeSchedule } from './EmployeeSchedule';
import { EmployeeQr, captureAttendanceQr } from './EmployeeQr';
type Employee={firstName:string;lastName:string;companyName:string;timezone:string};
export function EmployeePortal({api,onBack}:{api:string;onBack:()=>void}){
 const [refresh,setRefresh]=useState(0);
 useState(captureAttendanceQr);
 const [token,setToken]=useState(()=>sessionStorage.getItem('attendra_employee_session')||'');
 const [employee,setEmployee]=useState<Employee|null>(null);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[visible,setVisible]=useState(false);
 const company=new URLSearchParams(location.search).get('company')||'';
 const clear=()=>{sessionStorage.removeItem('attendra_employee_session');setToken('');setEmployee(null)};
 useEffect(()=>{if(!token)return;const abort=new AbortController();setError('');
  (async()=>{try{const headers={Authorization:`Bearer ${token}`};const a=await fetch(`${api}/v1/employee/me`,{headers,signal:abort.signal});if(a.status===401){clear();setError('Your session ended. Please sign in again.');return}if(!a.ok)throw Error();const profile=await a.json();if(!abort.signal.aborted){setEmployee(profile.employee)}}catch{if(!abort.signal.aborted)setError('Unable to load your account. Please try again.')}})();return()=>abort.abort();
 },[token,api,refresh]);
 const login=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(busy)return;const form=new FormData(event.currentTarget);setBusy(true);setError('');try{const response=await fetch(`${api}/v1/employee/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId:form.get('companyId'),employeeNumber:form.get('employeeNumber'),pin:form.get('pin')})});if(!response.ok){setError(response.status===429?'Too many attempts. Please wait 15 minutes before trying again.':response.status===400?'Please check your company ID, employee number and PIN.':'Employee number or PIN is incorrect.');return}const data=await response.json();sessionStorage.setItem('attendra_employee_session',data.token);setToken(data.token)}catch{setError('Cannot connect to Attendra. Check your connection and try again.')}finally{setBusy(false)}};
 const logout=async()=>{setBusy(true);setError('');try{const response=await fetch(`${api}/v1/employee/logout`,{method:'POST',headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw Error();sessionStorage.removeItem('attendra_pending_qr');clear()}catch{setError('Unable to sign out. Check your connection and try again.')}finally{setBusy(false)}};
 if(!token)return <main className="loginShell"><section className="loginCard"><span className="eyebrow">ATTENDRA EMPLOYEE</span><h1>Employee sign in</h1><p>Use the employee number and PIN provided by your manager.</p><form className="loginForm" onSubmit={login}><label>Company ID<input name="companyId" defaultValue={company} required readOnly={Boolean(company)}/></label><label>Employee number<input name="employeeNumber" autoComplete="username" maxLength={64} required/></label><label>PIN<input name="pin" type={visible?'text':'password'} inputMode="numeric" pattern="[0-9]{4,12}" autoComplete="current-password" required/></label><label className="checkLabel"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/>Show PIN</label>{error&&<div className="errorBox" role="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><button className="linkButton" type="button" onClick={onBack}>Admin / Manager sign in</button></form><p>Forgot your PIN? Ask your manager to reset it.</p></section></main>;
 return <main className="shell"><header><div><span className="eyebrow">{employee?.companyName||'ATTENDRA'}</span><h1>{employee?`Hello ${employee.firstName}`:'Loading your account…'}</h1></div><button className="linkButton" disabled={busy} onClick={logout}>Sign out</button></header>{error&&<div className="errorBox" role="alert">{error}<button onClick={()=>location.reload()}>Retry</button></div>}{employee&&<EmployeeQr api={api} token={token} timeZone={employee.timezone} onRecorded={()=>setRefresh(value=>value+1)}/>}{employee&&<EmployeeSchedule api={api} token={token} timeZone={employee.timezone} refresh={refresh}/>}</main>;
}
