import Fastify from 'fastify';
import cors from '@fastify/cors';
import { createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import { db, pingDatabase } from './db.js';

const app = Fastify({ logger: true });
const allowedOrigins = (process.env.CORS_ORIGIN ?? '').split(',').map(value => value.trim()).filter(Boolean);
await app.register(cors, { origin: allowedOrigins.length ? allowedOrigins : true });

const ADMIN_EMAIL = process.env.ADMIN_EMAIL ?? '';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD ?? '';
const ADMIN_COMPANY_ID = process.env.ADMIN_COMPANY_ID ?? '';
const ADMIN_TOKEN_SECRET = process.env.ADMIN_TOKEN_SECRET ?? '';
type AdminToken = { email: string; companyId: string; exp: number };
const safeEqual = (a:string,b:string)=>{const l=createHash('sha256').update(a).digest();const r=createHash('sha256').update(b).digest();return timingSafeEqual(l,r)};
const signAdminToken=(p:AdminToken)=>{const b=Buffer.from(JSON.stringify(p)).toString('base64url');const s=createHmac('sha256',ADMIN_TOKEN_SECRET).update(b).digest('base64url');return `${b}.${s}`};
const verifyAdminToken=(token:string):AdminToken|null=>{if(!ADMIN_TOKEN_SECRET)return null;const [b,s]=token.split('.');if(!b||!s)return null;const e=createHmac('sha256',ADMIN_TOKEN_SECRET).update(b).digest('base64url');if(!safeEqual(s,e))return null;try{const p=JSON.parse(Buffer.from(b,'base64url').toString('utf8')) as AdminToken;return p.email&&p.companyId&&p.exp>=Date.now()?p:null}catch{return null}};
const requireAdmin=(request:any,reply:any):AdminToken|null=>{const h=String(request.headers.authorization??'');const p=verifyAdminToken(h.startsWith('Bearer ')?h.slice(7):'');if(!p){reply.code(401).send({ok:false,error:'ADMIN_AUTH_REQUIRED'});return null}return p};

app.get('/health',async(_request,reply)=>{try{return{ok:true,service:'attendra-api',version:'0.5.0',database:'connected',databaseTime:await pingDatabase(),time:new Date().toISOString()}}catch(error){app.log.error(error);return reply.code(503).send({ok:false,service:'attendra-api',database:'unavailable',time:new Date().toISOString()})}});
app.post('/v1/admin/login',async(request,reply)=>{const p=z.object({email:z.email(),password:z.string().min(8).max(256)}).safeParse(request.body);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_LOGIN_REQUEST'});if(!ADMIN_EMAIL||!ADMIN_PASSWORD||!ADMIN_COMPANY_ID||!ADMIN_TOKEN_SECRET)return reply.code(503).send({ok:false,error:'ADMIN_NOT_CONFIGURED'});if(!safeEqual(p.data.email.trim().toLowerCase(),ADMIN_EMAIL.trim().toLowerCase())||!safeEqual(p.data.password,ADMIN_PASSWORD))return reply.code(401).send({ok:false,error:'INVALID_ADMIN_CREDENTIALS'});const expiresAt=Date.now()+8*60*60*1000;return{ok:true,token:signAdminToken({email:ADMIN_EMAIL,companyId:ADMIN_COMPANY_ID,exp:expiresAt}),expiresAt,companyId:ADMIN_COMPANY_ID,email:ADMIN_EMAIL}});

const attendanceSchema=z.object({companyId:z.uuid(),branchId:z.uuid(),deviceId:z.uuid(),employeeNumber:z.string().trim().min(1).max(64),pin:z.string().regex(/^\d{4,12}$/),action:z.enum(['CHECK_IN','CHECK_OUT']),occurredAt:z.iso.datetime().optional()});
app.post('/v1/attendance/events',async(request,reply)=>{const p=attendanceSchema.safeParse(request.body);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_REQUEST',details:p.error.flatten()});const i=p.data,o=i.occurredAt?new Date(i.occurredAt):new Date(),c=await db.connect();try{await c.query('BEGIN');const d=await c.query('select id from devices where id=$1 and company_id=$2 and branch_id=$3 and active=true for update',[i.deviceId,i.companyId,i.branchId]);if(!d.rowCount){await c.query('ROLLBACK');return reply.code(403).send({ok:false,error:'DEVICE_NOT_AUTHORISED'})}const er=await c.query(`select id,first_name,last_name from employees where company_id=$1 and employee_number=$2 and active=true and pin_hash=crypt($3,pin_hash) limit 1`,[i.companyId,i.employeeNumber,i.pin]);if(!er.rowCount){await c.query('ROLLBACK');return reply.code(401).send({ok:false,error:'INVALID_EMPLOYEE_OR_PIN'})}const e=er.rows[0];const sr=await c.query(`select id,starts_at,ends_at from shifts where company_id=$1 and branch_id=$2 and employee_id=$3 and $4::timestamptz between starts_at-interval '4 hours' and ends_at+interval '4 hours' order by abs(extract(epoch from(starts_at-$4::timestamptz))) limit 1`,[i.companyId,i.branchId,e.id,o.toISOString()]);const s=sr.rows[0]??null;let status:'ON_TIME'|'LATE'|'EARLY'|'UNSCHEDULED'='UNSCHEDULED';if(s&&i.action==='CHECK_IN'){const st=new Date(s.starts_at).getTime(),t=o.getTime(),g=300000;status=t>st+g?'LATE':t<st-g?'EARLY':'ON_TIME'}else if(s)status='ON_TIME';const ir=await c.query(`insert into attendance_events(company_id,branch_id,device_id,employee_id,shift_id,action,status,occurred_at) values($1,$2,$3,$4,$5,$6,$7,$8) returning id,action,status,occurred_at,received_at`,[i.companyId,i.branchId,i.deviceId,e.id,s?.id??null,i.action,status,o.toISOString()]);await c.query('update devices set last_seen_at=now() where id=$1',[i.deviceId]);await c.query(`insert into audit_log(company_id,actor_type,actor_id,action,entity_type,entity_id,metadata) values($1,'DEVICE',$2,$3,'ATTENDANCE_EVENT',$4,jsonb_build_object('employeeId',$5::uuid,'branchId',$6::uuid))`,[i.companyId,i.deviceId,i.action,ir.rows[0].id,e.id,i.branchId]);await c.query('COMMIT');return reply.code(201).send({ok:true,employee:{id:e.id,employeeNumber:i.employeeNumber,name:`${e.first_name} ${e.last_name}`},event:ir.rows[0]})}catch(error){await c.query('ROLLBACK');app.log.error(error);return reply.code(500).send({ok:false,error:'ATTENDANCE_WRITE_FAILED'})}finally{c.release()}});

app.get('/v1/companies/:companyId/attendance/recent',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({companyId:z.uuid()}).safeParse(request.params);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_COMPANY_ID'});if(p.data.companyId!==a.companyId)return reply.code(403).send({ok:false,error:'COMPANY_ACCESS_DENIED'});const r=await db.query(`select ae.id,ae.action,ae.status,ae.occurred_at as "occurredAt",e.employee_number as "employeeNumber",concat(e.first_name,' ',e.last_name) as "employeeName",b.name as "branchName" from attendance_events ae join employees e on e.id=ae.employee_id join branches b on b.id=ae.branch_id where ae.company_id=$1 order by ae.occurred_at desc limit 50`,[p.data.companyId]);return{ok:true,events:r.rows}});
app.get('/v1/companies/:companyId/attendance/summary',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({companyId:z.uuid()}).safeParse(request.params);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_COMPANY_ID'});if(p.data.companyId!==a.companyId)return reply.code(403).send({ok:false,error:'COMPANY_ACCESS_DENIED'});const r=await db.query(`with latest as(select distinct on(employee_id) employee_id,action from attendance_events where company_id=$1 order by employee_id,occurred_at desc) select (select count(*)::int from latest where action='CHECK_IN') as "checkedInNow",(select count(*)::int from attendance_events where company_id=$1 and status='LATE' and occurred_at::date=current_date) as "lateToday",(select count(*)::int from devices where company_id=$1 and active=true and(last_seen_at is null or last_seen_at<now()-interval '30 minutes')) as "offlineDevices"`,[p.data.companyId]);return{ok:true,summary:{...r.rows[0],absent:0}}});

app.get('/v1/admin/employees',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const r=await db.query(`select id,employee_number as "employeeNumber",first_name as "firstName",last_name as "lastName",hourly_worker as "hourlyWorker",active,created_at as "createdAt" from employees where company_id=$1 order by active desc,first_name,last_name`,[a.companyId]);return{ok:true,employees:r.rows}});
app.post('/v1/admin/employees',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({employeeNumber:z.string().trim().min(1).max(64),firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().min(1).max(100),pin:z.string().regex(/^\d{4,12}$/),hourlyWorker:z.boolean().default(false)}).safeParse(request.body);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_EMPLOYEE',details:p.error.flatten()});try{const r=await db.query(`insert into employees(company_id,employee_number,first_name,last_name,pin_hash,hourly_worker) values($1,$2,$3,$4,crypt($5,gen_salt('bf')),$6) returning id,employee_number as "employeeNumber",first_name as "firstName",last_name as "lastName",hourly_worker as "hourlyWorker",active,created_at as "createdAt"`,[a.companyId,p.data.employeeNumber,p.data.firstName,p.data.lastName,p.data.pin,p.data.hourlyWorker]);return reply.code(201).send({ok:true,employee:r.rows[0]})}catch(error:any){if(error?.code==='23505')return reply.code(409).send({ok:false,error:'EMPLOYEE_NUMBER_EXISTS'});app.log.error(error);return reply.code(500).send({ok:false,error:'EMPLOYEE_CREATE_FAILED'})}});
app.patch('/v1/admin/employees/:employeeId',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({employeeId:z.uuid()}).safeParse(request.params),b=z.object({firstName:z.string().trim().min(1).max(100).optional(),lastName:z.string().trim().min(1).max(100).optional(),pin:z.string().regex(/^\d{4,12}$/).optional(),hourlyWorker:z.boolean().optional(),active:z.boolean().optional()}).safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({ok:false,error:'INVALID_EMPLOYEE_UPDATE'});const r=await db.query(`update employees set first_name=coalesce($3,first_name),last_name=coalesce($4,last_name),pin_hash=case when $5::text is null then pin_hash else crypt($5,gen_salt('bf')) end,hourly_worker=coalesce($6,hourly_worker),active=coalesce($7,active) where id=$1 and company_id=$2 returning id,employee_number as "employeeNumber",first_name as "firstName",last_name as "lastName",hourly_worker as "hourlyWorker",active,created_at as "createdAt"`,[p.data.employeeId,a.companyId,b.data.firstName??null,b.data.lastName??null,b.data.pin??null,b.data.hourlyWorker??null,b.data.active??null]);if(!r.rowCount)return reply.code(404).send({ok:false,error:'EMPLOYEE_NOT_FOUND'});return{ok:true,employee:r.rows[0]}});

app.get('/v1/admin/branches',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const r=await db.query(`select b.id,b.name,b.timezone,b.address,b.active,b.created_at as "createdAt",count(distinct d.id)::int as "deviceCount" from branches b left join devices d on d.branch_id=b.id and d.active=true where b.company_id=$1 group by b.id order by b.active desc,b.name`,[a.companyId]);return{ok:true,branches:r.rows}});
app.post('/v1/admin/branches',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({name:z.string().trim().min(2).max(120),timezone:z.string().trim().min(2).max(100),address:z.string().trim().max(300).optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_BRANCH'});const r=await db.query(`insert into branches(company_id,name,timezone,address) values($1,$2,$3,$4) returning id,name,timezone,address,active,created_at as "createdAt"`,[a.companyId,p.data.name,p.data.timezone,p.data.address||null]);return reply.code(201).send({ok:true,branch:{...r.rows[0],deviceCount:0}})});
app.patch('/v1/admin/branches/:branchId',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({branchId:z.uuid()}).safeParse(request.params),b=z.object({name:z.string().trim().min(2).max(120).optional(),timezone:z.string().trim().min(2).max(100).optional(),address:z.string().trim().max(300).nullable().optional(),active:z.boolean().optional()}).safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({ok:false,error:'INVALID_BRANCH_UPDATE'});const r=await db.query(`update branches set name=coalesce($3,name),timezone=coalesce($4,timezone),address=case when $5::text is null then address else $5 end,active=coalesce($6,active) where id=$1 and company_id=$2 returning id,name,timezone,address,active,created_at as "createdAt"`,[p.data.branchId,a.companyId,b.data.name??null,b.data.timezone??null,b.data.address??null,b.data.active??null]);if(!r.rowCount)return reply.code(404).send({ok:false,error:'BRANCH_NOT_FOUND'});return{ok:true,branch:r.rows[0]}});

app.get('/v1/admin/devices',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const r=await db.query(`select d.id,d.name,d.branch_id as "branchId",b.name as "branchName",d.last_seen_at as "lastSeenAt",d.active,d.created_at as "createdAt",(d.active=true and d.last_seen_at is not null and d.last_seen_at>=now()-interval '30 minutes') as online from devices d join branches b on b.id=d.branch_id where d.company_id=$1 order by d.active desc,b.name,d.name`,[a.companyId]);return{ok:true,devices:r.rows}});
app.post('/v1/admin/devices',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({name:z.string().trim().min(2).max(120),branchId:z.uuid()}).safeParse(request.body);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_DEVICE'});const branch=await db.query(`select id from branches where id=$1 and company_id=$2 and active=true`,[p.data.branchId,a.companyId]);if(!branch.rowCount)return reply.code(404).send({ok:false,error:'BRANCH_NOT_FOUND'});const deviceKey=randomBytes(24).toString('base64url');const keyHash=createHash('sha256').update(deviceKey).digest('hex');const r=await db.query(`insert into devices(company_id,branch_id,name,device_key_hash) values($1,$2,$3,$4) returning id,name,branch_id as "branchId",last_seen_at as "lastSeenAt",active,created_at as "createdAt"`,[a.companyId,p.data.branchId,p.data.name,keyHash]);return reply.code(201).send({ok:true,device:{...r.rows[0],branchName:null,online:false},deviceKey})});
app.patch('/v1/admin/devices/:deviceId',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({deviceId:z.uuid()}).safeParse(request.params),b=z.object({name:z.string().trim().min(2).max(120).optional(),branchId:z.uuid().optional(),active:z.boolean().optional()}).safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({ok:false,error:'INVALID_DEVICE_UPDATE'});if(b.data.branchId){const branch=await db.query(`select id from branches where id=$1 and company_id=$2`,[b.data.branchId,a.companyId]);if(!branch.rowCount)return reply.code(404).send({ok:false,error:'BRANCH_NOT_FOUND'})}const r=await db.query(`update devices set name=coalesce($3,name),branch_id=coalesce($4,branch_id),active=coalesce($5,active) where id=$1 and company_id=$2 returning id,name,branch_id as "branchId",last_seen_at as "lastSeenAt",active,created_at as "createdAt"`,[p.data.deviceId,a.companyId,b.data.name??null,b.data.branchId??null,b.data.active??null]);if(!r.rowCount)return reply.code(404).send({ok:false,error:'DEVICE_NOT_FOUND'});return{ok:true,device:r.rows[0]}});
app.post('/v1/admin/devices/:deviceId/reset-key',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({deviceId:z.uuid()}).safeParse(request.params);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_DEVICE_ID'});const deviceKey=randomBytes(24).toString('base64url');const keyHash=createHash('sha256').update(deviceKey).digest('hex');const r=await db.query(`update devices set device_key_hash=$3 where id=$1 and company_id=$2 returning id,name`,[p.data.deviceId,a.companyId,keyHash]);if(!r.rowCount)return reply.code(404).send({ok:false,error:'DEVICE_NOT_FOUND'});return{ok:true,device:r.rows[0],deviceKey}});

app.get('/v1/admin/shifts',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const r=await db.query(`select s.id,s.employee_id as "employeeId",concat(e.first_name,' ',e.last_name) as "employeeName",e.employee_number as "employeeNumber",s.branch_id as "branchId",b.name as "branchName",s.starts_at as "startsAt",s.ends_at as "endsAt",s.break_minutes as "breakMinutes",s.created_at as "createdAt" from shifts s join employees e on e.id=s.employee_id join branches b on b.id=s.branch_id where s.company_id=$1 order by s.starts_at asc limit 250`,[a.companyId]);return{ok:true,shifts:r.rows}});
app.post('/v1/admin/shifts',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({employeeId:z.uuid(),branchId:z.uuid(),startsAt:z.iso.datetime(),endsAt:z.iso.datetime(),breakMinutes:z.number().int().min(0).max(720).default(0)}).safeParse(request.body);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_SHIFT',details:p.error.flatten()});if(new Date(p.data.endsAt).getTime()<=new Date(p.data.startsAt).getTime())return reply.code(400).send({ok:false,error:'SHIFT_END_MUST_BE_AFTER_START'});const [employee,branch]=await Promise.all([db.query(`select id from employees where id=$1 and company_id=$2 and active=true`,[p.data.employeeId,a.companyId]),db.query(`select id from branches where id=$1 and company_id=$2 and active=true`,[p.data.branchId,a.companyId])]);if(!employee.rowCount)return reply.code(404).send({ok:false,error:'EMPLOYEE_NOT_FOUND'});if(!branch.rowCount)return reply.code(404).send({ok:false,error:'BRANCH_NOT_FOUND'});const r=await db.query(`insert into shifts(company_id,branch_id,employee_id,starts_at,ends_at,break_minutes) values($1,$2,$3,$4,$5,$6) returning id,employee_id as "employeeId",branch_id as "branchId",starts_at as "startsAt",ends_at as "endsAt",break_minutes as "breakMinutes",created_at as "createdAt"`,[a.companyId,p.data.branchId,p.data.employeeId,p.data.startsAt,p.data.endsAt,p.data.breakMinutes]);return reply.code(201).send({ok:true,shift:r.rows[0]})});
app.patch('/v1/admin/shifts/:shiftId',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({shiftId:z.uuid()}).safeParse(request.params),b=z.object({employeeId:z.uuid().optional(),branchId:z.uuid().optional(),startsAt:z.iso.datetime().optional(),endsAt:z.iso.datetime().optional(),breakMinutes:z.number().int().min(0).max(720).optional()}).safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({ok:false,error:'INVALID_SHIFT_UPDATE'});const current=await db.query(`select * from shifts where id=$1 and company_id=$2`,[p.data.shiftId,a.companyId]);if(!current.rowCount)return reply.code(404).send({ok:false,error:'SHIFT_NOT_FOUND'});const row=current.rows[0];const employeeId=b.data.employeeId??row.employee_id,branchId=b.data.branchId??row.branch_id,startsAt=b.data.startsAt??new Date(row.starts_at).toISOString(),endsAt=b.data.endsAt??new Date(row.ends_at).toISOString();if(new Date(endsAt).getTime()<=new Date(startsAt).getTime())return reply.code(400).send({ok:false,error:'SHIFT_END_MUST_BE_AFTER_START'});const [employee,branch]=await Promise.all([db.query(`select id from employees where id=$1 and company_id=$2`,[employeeId,a.companyId]),db.query(`select id from branches where id=$1 and company_id=$2`,[branchId,a.companyId])]);if(!employee.rowCount)return reply.code(404).send({ok:false,error:'EMPLOYEE_NOT_FOUND'});if(!branch.rowCount)return reply.code(404).send({ok:false,error:'BRANCH_NOT_FOUND'});const r=await db.query(`update shifts set employee_id=$3,branch_id=$4,starts_at=$5,ends_at=$6,break_minutes=coalesce($7,break_minutes) where id=$1 and company_id=$2 returning id,employee_id as "employeeId",branch_id as "branchId",starts_at as "startsAt",ends_at as "endsAt",break_minutes as "breakMinutes",created_at as "createdAt"`,[p.data.shiftId,a.companyId,employeeId,branchId,startsAt,endsAt,b.data.breakMinutes??null]);return{ok:true,shift:r.rows[0]}});
app.delete('/v1/admin/shifts/:shiftId',async(request,reply)=>{const a=requireAdmin(request,reply);if(!a)return;const p=z.object({shiftId:z.uuid()}).safeParse(request.params);if(!p.success)return reply.code(400).send({ok:false,error:'INVALID_SHIFT_ID'});const linked=await db.query(`select 1 from attendance_events where shift_id=$1 limit 1`,[p.data.shiftId]);if(linked.rowCount)return reply.code(409).send({ok:false,error:'SHIFT_HAS_ATTENDANCE'});const r=await db.query(`delete from shifts where id=$1 and company_id=$2 returning id`,[p.data.shiftId,a.companyId]);if(!r.rowCount)return reply.code(404).send({ok:false,error:'SHIFT_NOT_FOUND'});return{ok:true}});

const port=Number(process.env.PORT??4000);await app.listen({port,host:'0.0.0.0'});